POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "d title",
  "author": "the author",
  "url": "www.google.com.sg",
  "likes": 9000
}

###
GET http://localhost:3003/api/blogs HTTP/1.1
